[package]
name = "wedb_pubsub"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/x-at-01/garnet_rust.git"
homepage = "https://github.com/x-at-01/garnet_rust/tree/main/wedb_pubsub"
description = "wedb_pubsub"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcode = "0.6.9"
bytes = "1.12.1"
crossfire = "3.1.20"
parking_lot = "0.12.5"
thiserror = "2.0.20"
wedb_resp = { version = "0.1.0", path = "../wedb_resp" }
whasher = { version = "0.1.0", path = "../../wedb_base/whasher" }
itoa = "1.0.18"

[dev-dependencies]
aok = "0.1.18"
ctor = "1.0.13"
fastrand = "2.5.0"
log = "0.4.34"
log_init = "0.1.39"

[lints]
workspace = true
