[package]
name = "wedb_hll"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/x-at-01/garnet_rust.git"
homepage = "https://github.com/x-at-01/garnet_rust/tree/main/wedb_hll"
description = "wedb_hll"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcode = "0.6.9"
thiserror = "2.0.20"
whasher = { version = "0.1.0", path = "../../wedb_base/whasher" }

[dev-dependencies]
aok = "0.1.18"
ctor = "1.0.13"
itoa = "1.0.18"
log = "0.4.34"
log_init = "0.1.39"

[lints]
workspace = true
