[package]
name = "wedb_bench"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/x-at-01/garnet_rust.git"
homepage = "https://github.com/x-at-01/garnet_rust/tree/main/wedb_bench"
description = "wedb_bench"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
compio = { version = "0.19.2", features = ["runtime"] }
fastrand = "2.5.0"
fjall = "3.1.10"
itoa = "1.0.18"
libc = "0.2.189"
markdown-table-formatter = "0.3.0"
mimalloc = "0.1.52"
rocksdb = "0.25.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml_ng = "0.10.0"
tempfile = "3.27.0"
thiserror = "2.0.20"
wbftree = { version = "0.1.0", path = "../../wedb_base/wbftree" }
wdev = { version = "0.1.0", path = "../../wedb_base/wdev" }
whlog = { version = "0.1.0", path = "../../wedb_base/whlog" }
wedb_redis = { version = "0.1.0", path = "../wedb_redis" }
wkv = { version = "0.1.0", path = "../../wedb_base/wkv" }
wedb_zset = { version = "0.1.0", path = "../wedb_zset" }
zmij = "1.0.23"

[dev-dependencies]
aok = "0.1.18"
criterion = "0.8.2"
ctor = "1.0.13"
log = "0.4.34"
log_init = "0.1.39"

[[bench]]
name = "bench"
harness = false


[lints]
workspace = true

[[bin]]
name = "wedb-bench"
path = "src/main.rs"
