[package]
name = "wedb_vector"
version = "0.1.0"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/x-at-01/garnet_rust.git"
homepage = "https://github.com/x-at-01/garnet_rust/tree/main/wedb_vector"
description = "wedb_vector"
keywords = []
categories = []

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
fastrand = "2.5.0"
gxhash = "3.5.0"
parking_lot = "0.12.5"
thiserror = "2.0.20"
whasher = { version = "0.1.0", path = "../../wedb_base/whasher" }

[dev-dependencies]
aok = "0.1.18"
ctor = "1.0.13"
log = "0.4.34"
log_init = "0.1.39"

[lints]
workspace = true
